# Generated by Django 2.2.23 on 2021-05-24 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0004_auto_20210524_1930'),
        ('estoque', '0006_protocoloentrega_estoque_atualizado'),
    ]

    operations = [
        migrations.AddField(
            model_name='estoque',
            name='fornecedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='produto.Fornecedor'),
        ),
        migrations.AddField(
            model_name='estoque',
            name='obs',
            field=models.CharField(blank=True, max_length=222, null=True, verbose_name='Observação'),
        ),
        migrations.AddField(
            model_name='protocoloentrega',
            name='obs',
            field=models.CharField(blank=True, max_length=222, null=True, verbose_name='Observação'),
        ),
        migrations.AddField(
            model_name='protocoloentregaitens',
            name='fornecedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='produto.Fornecedor'),
        ),
    ]
