# Generated by Django 2.2.23 on 2021-05-25 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0008_estoqueitens_preco_pro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estoqueitens',
            name='preco_pro',
            field=models.DecimalField(decimal_places=2, max_digits=7, verbose_name='preço'),
        ),
    ]
