# Generated by Django 2.2.23 on 2021-05-25 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0009_auto_20210525_1751'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estoqueitens',
            old_name='preco_pro',
            new_name='preco_p',
        ),
    ]
