# Generated by Django 2.2.23 on 2021-05-25 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0010_auto_20210525_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estoqueitens',
            name='preco_p',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True, verbose_name='preço'),
        ),
    ]
