# Generated by Django 2.2.23 on 2021-05-25 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0012_auto_20210525_1754'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estoqueitens',
            name='preco_pro',
        ),
    ]
