# Generated by Django 2.2.23 on 2021-05-25 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0013_remove_estoqueitens_preco_pro'),
    ]

    operations = [
        migrations.AddField(
            model_name='estoqueitens',
            name='preco_pro',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='preço'),
        ),
    ]
