# Generated by Django 2.2.23 on 2021-05-25 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0004_auto_20210524_1930'),
        ('estoque', '0014_estoqueitens_preco_pro'),
    ]

    operations = [
        migrations.AddField(
            model_name='estoqueitens',
            name='fornecedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='produto.Fornecedor'),
        ),
    ]
